### ISSUE TITLE
Systems w/ dual graphics require a workaround

### ISSUE THREAD

**Issue by zelikos** [zelikos/davincibox#40]
> On a laptop with Nvidia, DaVinci doesn't use the dGPU by default, and GNOME's "launch with discrete GPU" option doesn't work because it sets environment variables which don't get passed through by distrobox. The fix I found was editing the desktop file and replacing
> 
> ```desktop
> Exec=/usr/bin/distrobox-enter -n davincibox -- /opt/resolve/bin/resolve %u
> ```
> 
> with
> 
> ```desktop
> Exec=/usr/bin/distrobox-enter -n davincibox -- env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia /opt/resolve/bin/resolve %u
> ```
> 

_Originally posted by @flexagoon in https://github.com/zelikos/davincibox/issues/21#issuecomment-1827508764_

Ideally, we'd handle this automatically, but in the short term we can add an argument for `add-davinci-launcher` and the `run-davinci` script to apply the environment variables here.

**Comment by not-a-dev-stein** [comment]
This finally fixed the issue I was having (error 999), thanks!

**Comment by not-a-dev-stein** [comment]
I'm not sure what's changed in the meantime, but ever since updating to the 555 NVIDIA drivers, something broke, both distrobox and toolbox don't recognize CUDA anymore and I get the "Failed to initialize GPU" error whenever I launch Davinci, which I'm working around by using the integrated GPU with rusticl, but it's obviously much, much slower than the dedicated GPU.

**Comment by flexagoon** [comment]
@not-a-dev-stein did you also update the driver inside of the distrobox?

**Comment by not-a-dev-stein** [comment]
> @not-a-dev-stein did you also update the driver inside of the distrobox?

Yup, I'm on latest on both. If I don't run the command to open Davinci with rusticl it gives out an error and gives me the menu to change GPU configuration, where I can see it detects both the integrated and the NVIDIA GPU but only gives OpenCL as an option, and the program doesn't run at all when I restart, it always gives me the GPU error. With rusticl at least it runs on the integrated GPU.

**Comment by zelikos** [comment]
If things are broken in both distrobox *and* toolbox, my guess would be something was broken on the Nvidia driver side. I unable to troubleshoot this directly since I don't have an Nvidia GPU, though

**Comment by Beryesa** [comment]
Could distrobox itself further handle these nvidia ones (and DRI_PRIME) which it gets from gnome, perhaps on the upstream project?

**Comment by TuxManxD** [comment]
this didn't work for me on arch linux for some reason I have an rtx 3050 mobile as my dgpu and it fails to launch here is the output when running in terminal
[crash.txt](https://github.com/user-attachments/files/18298993/crash.txt)
![image](https://github.com/user-attachments/assets/6ff38c6d-1d2d-40a8-81ea-b42714f4bf4a)

**Comment by zelikos** [comment]
@TuxManxD Seems similar to one of the problems encountered in #131, where they also use Hyprland. This is what they did as a workaround:

> My exec now looks like:
`Exec=distrobox-enter -n davincibox -- bash -cl "export __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia QT_QPA_PLATFORM=xcb && /opt/resolve/bin/resolve %u"`

**Comment by TuxManxD** [comment]
@zelikos I tried to use that workaround and I got a different error 
[crash.txt](https://github.com/user-attachments/files/18301157/crash.txt)

**Comment by TuxManxD** [comment]
@zelikos I even tried with toolbox with the same error

**Comment by zelikos** [comment]
@TuxManxD I'm gonna move this into a separate issue

**Comment by Filip-K** [comment]
To get back to the core of the issue, @zelikos, do you think that there might be a way to automatically apply the workarounds for dual-GPU laptops during installation? Perhaps `setup.sh` could check for `switcherooctl` on the host, and if it exists, add the environment variables it returns to the launcher file?

If it's not so easy, perhaps we could just have a warning in the README pointing to this issue. (And rename it so as not to suggest it's Nvidia-only, because the underlying problem occurs also on AMD.)

**Comment by Filip-K** [comment]
You might be right that, now that you've got the dual-GPU issue out of the way, you might be facing a different problem that's actually not dual-GPU related. (So the discussion might have to move again to keep this issue focused, but let's see.)

Could you post the content of `~/.local/share/DaVinciResolve/logs/ResolveDebug.txt` just after the error occurred?

**Comment by zelikos** [comment]
Tentatively, this has now been fixed by #183. If you've been affected by this issue, please retest when you're able to. If there are still problems with multi-GPU setups, I can reopen this.

**Comment by zelikos** [comment]
> Thanks for the fix [@zelikos](https://github.com/zelikos) ! I just made a fresh install to test it and unfortunately it doesn't seem to solve the issue on my Framework, I still need to add the environment variable manually to the Exec line. Specifically, in my new install the Exec line reads
> 
> ```
> distrobox-enter -n davincibox -- /usr/bin/run-davinci /opt/resolve/bin/resolve %u
> ```
> 
> And that gives me the same `Failed to create OpenCL context` error as before. I need to manually modify it to
> 
> ```
> distrobox-enter -n davincibox -- env DRI_PRIME=pci-0000_03_00_0 /usr/bin/run-davinci /opt/resolve/bin/resolve %u
> ```
> 
> in order for Resolve to play any media.

Did you try the [new troubleshooting steps](https://github.com/zelikos/davincibox?tab=readme-ov-file#dual-gpu-systems) for multi-GPU systems? It might be that switcherooctl is incorrectly choosing the iGPU as the default over the dGPU. The end result should be the same as your current workaround, anyway, but I'm curious.

**Comment by Filip-K** [comment]
Thanks for your reply! I overlooked the README change, sorry for that! I have just tried the steps on my machine and they don't seem to work exactly as written. First, _inside the container_ `switcherooctl list` returns nothing. Trying `switcherooctl -v` gives
```
Traceback (most recent call last):
  File "/usr/sbin/switcherooctl", line 187, in <module>
    launch(args, gpu)
    ~~~~~~^^^^^^^^^^^
  File "/usr/sbin/switcherooctl", line 66, in launch
    os.execvp(args[0], args)
    ~~~~~~~~~^^^^^^^^^^^^^^^
  File "<frozen os>", line 611, in execvp
  File "<frozen os>", line 653, in _execvpe
  File "<frozen os>", line 644, in _execvpe
FileNotFoundError: [Errno 2] No such file or directory
```

Then, I can still get the GPU number (1 in my case) using switcherooctl on the host, but back in the container running `sed -i "s,switcherooctl launch,switcherooctl launch -g 1," /usr/bin/run-davinci` throws `sed: couldn't open temporary file /usr/bin/sedA7PxtV: Permission denied`.  I had to prepend the command with sudo. Finally, even with `switcherooctl launch -g 1` in my `/usr/bin/run-davinci` I still get `Failed to create OpenCL context`. That is probably because switcherooctl inside the container bugs out and the `-g` flag has no effect. It works if I change the run line to `env DRI_PRIME=pci-0000_03_00_0 switcherooctl launch $DAVINCI_BIN`.

**Comment by zelikos** [comment]
> Then, I can still get the GPU number (1 in my case) using switcherooctl on the host, but back in the container running `sed -i "s,switcherooctl launch,switcherooctl launch -g 1," /usr/bin/run-davinci` throws `sed: couldn't open temporary file /usr/bin/sedA7PxtV: Permission denied`. I had to prepend the command with sudo.

Oh, oops, that's an oversight on my part; the `sed` command does indeed require sudo here. Fixed in 34832177f3b3a018ab1df54c4d48a73fee42597c

As for the rest: this sounds like an issue either with switcherooctl itself, or some missing requirements that either need added into davincibox or noted in the README. I'll move this into a separate issue
